apiVersion: velero.io/v1
kind: Backup
metadata:
  name: test-backup
  namespace: openshift-adp
spec:
  includedNamespaces:
  - backup-oadp
  includedResources:
  - namespace
  - deployments
  - services
  - secrets
